# Generated by Django 4.0.6 on 2022-08-03 21:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centerline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('line', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FootprintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('colour', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour1', models.JSONField()),
                ('colour2', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.takeoffcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KP_beg', models.FloatField()),
                ('KP_end', models.FloatField(blank=True)),
                ('text_shrt', models.TextField()),
                ('text_long', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('value', models.FloatField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.takeofffamily')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.takeoffrevision')),
            ],
        ),
        migrations.CreateModel(
            name='FootprintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('description', models.TextField(blank=True)),
                ('centerline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centerline')),
                ('footprint_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.footprinttype')),
            ],
        ),
        migrations.CreateModel(
            name='ElevationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KP', models.FloatField()),
                ('elevation', models.FloatField()),
                ('centerline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centerline')),
            ],
        ),
        migrations.CreateModel(
            name='ChainagePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('measure', models.FloatField()),
                ('display', models.CharField(blank=True, max_length=64)),
                ('centerline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centerline')),
            ],
        ),
        migrations.AddField(
            model_name='centerline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
