# Generated by Django 4.0.6 on 2022-08-04 17:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_centerline_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevationpoint',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
