# Generated by Django 4.0.6 on 2022-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_takeofffamily_colour2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeoffpoint',
            old_name='KP_beg',
            new_name='chainage_beg',
        ),
        migrations.RenameField(
            model_name='takeoffpoint',
            old_name='KP_end',
            new_name='chainage_end',
        ),
        migrations.AlterField(
            model_name='chainagepoint',
            name='display',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
