# Generated by Django 4.0.6 on 2022-08-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerline',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centerline',
            name='elevation',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='centerline',
            name='footprint',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='takeoff',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
