# Generated by Django 4.0.6 on 2022-08-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_elevationpoint_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevationpoint',
            old_name='KP',
            new_name='chainage',
        ),
    ]
