# Generated by Django 4.0.6 on 2022-08-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_kp_elevationpoint_chainage'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeofffamily',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
