# Generated by Django 4.0.6 on 2022-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_takeofffamily_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeofffamily',
            name='colour2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='takeoffpoint',
            name='KP_end',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
