# Generated by Django 4.0.6 on 2022-08-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_takeoffpoint_symbol_alter_takeoffpoint_text_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainagepoint',
            name='display',
        ),
        migrations.RemoveField(
            model_name='takeoffpoint',
            name='project',
        ),
        migrations.AddField(
            model_name='takeoffcategory',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
            preserve_default=False,
        ),
    ]
